[seedbot]
log_level = "DEBUG"

[discord]
discord_token = "DISCORD_TOKEN"
# discord_guild_id = "DISCORD_GUILD_ID"

[database.postgres]
db_user = "seedbot"
db_password = "seedbot"
db_url = "localhost"
db_port = 5432
db_name = "seedbot"

[hell_let_loose]
rcon_url = ["https://rcon_server_1.com:8080", "https://rcon_server_2.com:8081"]
rcon_user = "rcon_user"
rcon_password = "rcon_password"
seeding_threshold = 40
seeder_vip_reward_hours = 1
seeder_reward_message = "You've earned 1 hour of VIP for seeding!"
seeding_start_time_utc = "11:00"
seeding_end_time_utc = "20:00"
max_log_parse_mins = 30
allow_messages_to_players = false
